application:
    build: .
    command: nodemon --harmony /application/src/index.js
    links:
        - postgres
    ports:
        - "3000:3000"
    volumes:
        - ./src:/application/src
    environment:
        - MAILGUN_KEY

postgres:
    image: postgres
