application:
    build: .
    command: nodemon --harmony /application/src/index.js
    links:
        - postgres
        - redis
    ports:
        - "3000:3000"
        - "3001:3001"
    volumes:
        - ./src:/application/src
    environment:
        - MAILGUN_KEY

postgres:
    image: postgres

redis:
    image: redis
